services:
    laravelapp:
        container_name: laravel-app
        image: laravel-app
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./app:/var/www/app
            - ./resources:/var/www/resources
            - ./routes:/var/www/routes
            - ./config:/var/www/config
            - ./database:/var/www/database
            - ./.env:/var/www/.env
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
    db:
        container_name: espelho-db
        image: postgres:17
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123@senha
            - POSTGRES_DB=espelho-docker
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d espelho-docker"]
            interval: 5s
            timeout: 5s
            retries: 10 

volumes:
    pgdata: {}
    pgadmin_data: {}
